name: Build Maven Project CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Setup postgres environment
        run: docker compose -f ./.docker/docker-compose.yml up -d
      - name: Build project with Maven
        env:
          APP_ENV: production
          DB_URL: jdbc:postgresql://db:5432/postgres
          DB_USER: dba
          DB_PWD: changeme
        run: mvn -B package --file pom.xml
