name: Build Maven Project CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Setup postgres environment
        run: docker compose -f ./.docker/docker-compose.yml up -d db
      - name: Wait for postgres to start
        run: timeout 90s bash -c "until docker exec db pg_isready ; do sleep 5 ; done"
      - name: Build project with Maven
        run: mvn -B package --file pom.xml
